<form method="POST" action="/edit/<?= $created; ?>">
  <?php if (isset($error)) { ?>
    <div class="alert alert-warning"><?= htmlentities($error); ?></div>
  <?php } ?>
  <input type="hidden" name="created" value="<?= $created; ?>">
  <label>
    Title:
    <input type="text" name="title" value="<?= htmlentities($title); ?>">
  </label>
  <br>
  <textarea name="body" style="width: 100%; height: 20em;"><?= htmlentities($body); ?></textarea>
  <br>
  <input type="submit" value="Save">
</form>
