<?php use Fifty\_; ?>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><?= htmlentities($title) ?></a>
      </div>
      <?php if (_::loggedin()) { ?>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="//logout@<?= $_SERVER["SERVER_NAME"] ?>/logout">Logout <?= htmlentities(_::loggedin()) ?></a></li>
      </ul>
      <?php } ?>
    </div>
  </nav>
  <div class="container">
    <?php foreach($posts as $post) { include "post.phtml"; } ?>
  </div>
